name: Go
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.12-alpine
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    env:
      TEST_RESULTS: /tmp/test-results
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        CONTACTS_DB_URL: "postgres://postgres@localhost:5432/postgres?sslmode=disable"
        CONTACTS_DB_MIGRATIONS: /home/circleci/project/db/migrations
      run: go test -v ./...
